// Mocks generated by Mockito 5.4.4 from annotations
// in pcp/test/infra/repositories/variable/config_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pcp/infra/datasource/shared_preferences/config_datasource_shared_preferences.dart'
    as _i3;
import 'package:pcp/infra/model/shared_preferences/config_shared_preferences_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConfigSharedPreferencesModel_0 extends _i1.SmartFake
    implements _i2.ConfigSharedPreferencesModel {
  _FakeConfigSharedPreferencesModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigDatasourceSharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigDatasourceSharedPreferences extends _i1.Mock
    implements _i3.ConfigDatasourceSharedPreferences {
  MockConfigDatasourceSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> hasConfig() => (super.noSuchMethod(
        Invocation.method(
          #hasConfig,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.ConfigSharedPreferencesModel> getConfig() =>
      (super.noSuchMethod(
        Invocation.method(
          #getConfig,
          [],
        ),
        returnValue: _i4.Future<_i2.ConfigSharedPreferencesModel>.value(
            _FakeConfigSharedPreferencesModel_0(
          this,
          Invocation.method(
            #getConfig,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ConfigSharedPreferencesModel>);
}
