// Mocks generated by Mockito 5.4.4 from annotations
// in pcp/test/unit/domain/repository/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pcp/domain/entities/stable/colab.dart' as _i9;
import 'package:pcp/domain/entities/stable/equip.dart' as _i11;
import 'package:pcp/domain/entities/stable/local.dart' as _i13;
import 'package:pcp/domain/entities/stable/terceiro.dart' as _i15;
import 'package:pcp/domain/entities/stable/visitante.dart' as _i17;
import 'package:pcp/domain/entities/variable/config.dart' as _i7;
import 'package:pcp/domain/errors/errors.dart' as _i6;
import 'package:pcp/domain/repositories/stable/colab_repository.dart' as _i8;
import 'package:pcp/domain/repositories/stable/equip_repository.dart' as _i10;
import 'package:pcp/domain/repositories/stable/local_repository.dart' as _i12;
import 'package:pcp/domain/repositories/stable/terceiro_repository.dart'
    as _i14;
import 'package:pcp/domain/repositories/stable/visitante_repository.dart'
    as _i16;
import 'package:pcp/domain/repositories/variable/config_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigRepository extends _i1.Mock implements _i3.ConfigRepository {
  MockConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> has() => (super.noSuchMethod(
        Invocation.method(
          #has,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String> getSenha() => (super.noSuchMethod(
        Invocation.method(
          #getSenha,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSenha,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<num> getNroAparelho() => (super.noSuchMethod(
        Invocation.method(
          #getNroAparelho,
          [],
        ),
        returnValue: _i4.Future<num>.value(0),
      ) as _i4.Future<num>);

  @override
  _i4.Future<String> getVersion() => (super.noSuchMethod(
        Invocation.method(
          #getVersion,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getVersion,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, num>> send(_i7.Config? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [config],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, num>>.value(
            _FakeEither_0<_i6.Failure, num>(
          this,
          Invocation.method(
            #send,
            [config],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, num>>);

  @override
  _i4.Future<void> save(_i7.Config? config) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ColabRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockColabRepository extends _i1.Mock implements _i8.ColabRepository {
  MockColabRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> addAllColab(
          List<_i9.Colab>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllColab,
          [list],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addAllColab,
            [list],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> deleteAllColab() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllColab,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllColab,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i9.Colab>>> recoverAllColab(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverAllColab,
          [token],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, List<_i9.Colab>>>.value(
            _FakeEither_0<_i6.Failure, List<_i9.Colab>>(
          this,
          Invocation.method(
            #recoverAllColab,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i9.Colab>>>);
}

/// A class which mocks [EquipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEquipRepository extends _i1.Mock implements _i10.EquipRepository {
  MockEquipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> addAllEquip(
          List<_i11.Equip>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllEquip,
          [list],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addAllEquip,
            [list],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> deleteAllEquip() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllEquip,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllEquip,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i11.Equip>>> recoverAllEquip(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverAllEquip,
          [token],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i11.Equip>>>.value(
                _FakeEither_0<_i6.Failure, List<_i11.Equip>>(
          this,
          Invocation.method(
            #recoverAllEquip,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i11.Equip>>>);
}

/// A class which mocks [LocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalRepository extends _i1.Mock implements _i12.LocalRepository {
  MockLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> addAllLocal(
          List<_i13.Local>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllLocal,
          [list],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addAllLocal,
            [list],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> deleteAllLocal() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllLocal,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllLocal,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i13.Local>>> recoverAllLocal(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverAllLocal,
          [token],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i13.Local>>>.value(
                _FakeEither_0<_i6.Failure, List<_i13.Local>>(
          this,
          Invocation.method(
            #recoverAllLocal,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i13.Local>>>);
}

/// A class which mocks [TerceiroRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTerceiroRepository extends _i1.Mock
    implements _i14.TerceiroRepository {
  MockTerceiroRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> addAllTerceiro(
          List<_i15.Terceiro>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllTerceiro,
          [list],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addAllTerceiro,
            [list],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> deleteAllTerceiro() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllTerceiro,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllTerceiro,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i15.Terceiro>>> recoverAllTerceiro(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverAllTerceiro,
          [token],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i15.Terceiro>>>.value(
                _FakeEither_0<_i6.Failure, List<_i15.Terceiro>>(
          this,
          Invocation.method(
            #recoverAllTerceiro,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i15.Terceiro>>>);
}

/// A class which mocks [VisitanteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisitanteRepository extends _i1.Mock
    implements _i16.VisitanteRepository {
  MockVisitanteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> addAllVisitante(
          List<_i17.Visitante>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllVisitante,
          [list],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #addAllVisitante,
            [list],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, bool>> deleteAllVisitante() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllVisitante,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, bool>>.value(
            _FakeEither_0<_i6.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllVisitante,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, List<_i17.Visitante>>> recoverAllVisitante(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverAllVisitante,
          [token],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, List<_i17.Visitante>>>.value(
                _FakeEither_0<_i6.Failure, List<_i17.Visitante>>(
          this,
          Invocation.method(
            #recoverAllVisitante,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, List<_i17.Visitante>>>);
}
