// Mocks generated by Mockito 5.4.4 from annotations
// in pcp/test/unit/infra/datasource/mock_datasource.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pcp/domain/errors/errors.dart' as _i9;
import 'package:pcp/infra/datasource/floor/stable/colab_floor_datasource.dart'
    as _i8;
import 'package:pcp/infra/datasource/floor/stable/equip_floor_datasource.dart'
    as _i13;
import 'package:pcp/infra/datasource/floor/stable/local_floor_datasource.dart'
    as _i17;
import 'package:pcp/infra/datasource/floor/stable/terceiro_floor_datasource.dart'
    as _i21;
import 'package:pcp/infra/datasource/floor/stable/visitante_floor_datasource.dart'
    as _i25;
import 'package:pcp/infra/datasource/shared_preferences/config_shared_preferences_datasource.dart'
    as _i5;
import 'package:pcp/infra/datasource/web_preferences/stable/colab_web_service_datasource.dart'
    as _i11;
import 'package:pcp/infra/datasource/web_preferences/stable/equip_web_service_datasource.dart'
    as _i15;
import 'package:pcp/infra/datasource/web_preferences/stable/local_web_service_datasource.dart'
    as _i19;
import 'package:pcp/infra/datasource/web_preferences/stable/terceiro_web_service_datasource.dart'
    as _i23;
import 'package:pcp/infra/datasource/web_preferences/stable/visitante_web_service_datasource.dart'
    as _i27;
import 'package:pcp/infra/datasource/web_preferences/variable/config_web_service_datasource.dart'
    as _i7;
import 'package:pcp/infra/model/floor/stable/colab_floor_model.dart' as _i10;
import 'package:pcp/infra/model/floor/stable/equip_floor_model.dart' as _i14;
import 'package:pcp/infra/model/floor/stable/local_floor_model.dart' as _i18;
import 'package:pcp/infra/model/floor/stable/terceiro_floor_model.dart' as _i22;
import 'package:pcp/infra/model/floor/stable/visitante_floor_model.dart'
    as _i26;
import 'package:pcp/infra/model/shared_preferences/config_shared_preferences_model.dart'
    as _i2;
import 'package:pcp/infra/model/web_service/stable/colab_web_service_model.dart'
    as _i12;
import 'package:pcp/infra/model/web_service/stable/equip_web_service_model.dart'
    as _i16;
import 'package:pcp/infra/model/web_service/stable/local_web_service_model.dart'
    as _i20;
import 'package:pcp/infra/model/web_service/stable/terceiro_web_service_model.dart'
    as _i24;
import 'package:pcp/infra/model/web_service/stable/visitante_web_service_model.dart'
    as _i28;
import 'package:pcp/infra/model/web_service/variable/config_web_service_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConfigSharedPreferencesModel_0 extends _i1.SmartFake
    implements _i2.ConfigSharedPreferencesModel {
  _FakeConfigSharedPreferencesModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigWebServiceModelInput_1 extends _i1.SmartFake
    implements _i3.ConfigWebServiceModelInput {
  _FakeConfigWebServiceModelInput_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigSharedPreferencesDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigSharedPreferencesDatasource extends _i1.Mock
    implements _i5.ConfigSharedPreferencesDatasource {
  MockConfigSharedPreferencesDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> hasConfig() => (super.noSuchMethod(
        Invocation.method(
          #hasConfig,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.ConfigSharedPreferencesModel> getConfig() =>
      (super.noSuchMethod(
        Invocation.method(
          #getConfig,
          [],
        ),
        returnValue: _i6.Future<_i2.ConfigSharedPreferencesModel>.value(
            _FakeConfigSharedPreferencesModel_0(
          this,
          Invocation.method(
            #getConfig,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ConfigSharedPreferencesModel>);

  @override
  _i6.Future<void> salveConfig(
          _i2.ConfigSharedPreferencesModel? configSharedPreferencesModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #salveConfig,
          [configSharedPreferencesModel],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ConfigWebServiceDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigWebServiceDatasource extends _i1.Mock
    implements _i7.ConfigWebServiceDatasource {
  MockConfigWebServiceDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.ConfigWebServiceModelInput> sendConfig(
          _i3.ConfigWebServiceModelOutput? configWebServiceModelOutput) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendConfig,
          [configWebServiceModelOutput],
        ),
        returnValue: _i6.Future<_i3.ConfigWebServiceModelInput>.value(
            _FakeConfigWebServiceModelInput_1(
          this,
          Invocation.method(
            #sendConfig,
            [configWebServiceModelOutput],
          ),
        )),
      ) as _i6.Future<_i3.ConfigWebServiceModelInput>);
}

/// A class which mocks [ColabFloorDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockColabFloorDatasource extends _i1.Mock
    implements _i8.ColabFloorDatasource {
  MockColabFloorDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> addAllColab(
          List<_i10.ColabFloorModel>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllColab,
          [list],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #addAllColab,
            [list],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> deleteAllColab() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllColab,
          [],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllColab,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);
}

/// A class which mocks [ColabWebServiceDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockColabWebServiceDatasource extends _i1.Mock
    implements _i11.ColabWebServiceDatasource {
  MockColabWebServiceDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i12.ColabWebServiceModelInput>> getAllColab(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllColab,
          [token],
        ),
        returnValue: _i6.Future<List<_i12.ColabWebServiceModelInput>>.value(
            <_i12.ColabWebServiceModelInput>[]),
      ) as _i6.Future<List<_i12.ColabWebServiceModelInput>>);
}

/// A class which mocks [EquipFloorDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEquipFloorDatasource extends _i1.Mock
    implements _i13.EquipFloorDatasource {
  MockEquipFloorDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> addAllEquip(
          List<_i14.EquipFloorModel>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllEquip,
          [list],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #addAllEquip,
            [list],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> deleteAllEquip() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllEquip,
          [],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllEquip,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);
}

/// A class which mocks [EquipWebServiceDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEquipWebServiceDatasource extends _i1.Mock
    implements _i15.EquipWebServiceDatasource {
  MockEquipWebServiceDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i16.EquipWebServiceModelInput>> getAllEquip(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEquip,
          [token],
        ),
        returnValue: _i6.Future<List<_i16.EquipWebServiceModelInput>>.value(
            <_i16.EquipWebServiceModelInput>[]),
      ) as _i6.Future<List<_i16.EquipWebServiceModelInput>>);
}

/// A class which mocks [LocalFloorDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalFloorDatasource extends _i1.Mock
    implements _i17.LocalFloorDatasource {
  MockLocalFloorDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> addAllLocal(
          List<_i18.LocalFloorModel>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllLocal,
          [list],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #addAllLocal,
            [list],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> deleteAllLocal() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllLocal,
          [],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllLocal,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);
}

/// A class which mocks [LocalWebServiceDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalWebServiceDatasource extends _i1.Mock
    implements _i19.LocalWebServiceDatasource {
  MockLocalWebServiceDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i20.LocalWebServiceModelInput>> getAllLocal(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLocal,
          [token],
        ),
        returnValue: _i6.Future<List<_i20.LocalWebServiceModelInput>>.value(
            <_i20.LocalWebServiceModelInput>[]),
      ) as _i6.Future<List<_i20.LocalWebServiceModelInput>>);
}

/// A class which mocks [TerceiroFloorDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTerceiroFloorDatasource extends _i1.Mock
    implements _i21.TerceiroFloorDatasource {
  MockTerceiroFloorDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> addAllTerceiro(
          List<_i22.TerceiroFloorModel>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllTerceiro,
          [list],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #addAllTerceiro,
            [list],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> deleteAllTerceiro() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllTerceiro,
          [],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllTerceiro,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);
}

/// A class which mocks [TerceiroWebServiceDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTerceiroWebServiceDatasource extends _i1.Mock
    implements _i23.TerceiroWebServiceDatasource {
  MockTerceiroWebServiceDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i24.TerceiroWebServiceModelInput>> getAllTerceiro(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTerceiro,
          [token],
        ),
        returnValue: _i6.Future<List<_i24.TerceiroWebServiceModelInput>>.value(
            <_i24.TerceiroWebServiceModelInput>[]),
      ) as _i6.Future<List<_i24.TerceiroWebServiceModelInput>>);
}

/// A class which mocks [VisitanteFloorDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisitanteFloorDatasource extends _i1.Mock
    implements _i25.VisitanteFloorDatasource {
  MockVisitanteFloorDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> addAllVisitante(
          List<_i26.VisitanteFloorModel>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllVisitante,
          [list],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #addAllVisitante,
            [list],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);

  @override
  _i6.Future<_i4.Either<_i9.Failure, bool>> deleteAllVisitante() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllVisitante,
          [],
        ),
        returnValue: _i6.Future<_i4.Either<_i9.Failure, bool>>.value(
            _FakeEither_2<_i9.Failure, bool>(
          this,
          Invocation.method(
            #deleteAllVisitante,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i9.Failure, bool>>);
}

/// A class which mocks [VisitanteWebServiceDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisitanteWebServiceDatasource extends _i1.Mock
    implements _i27.VisitanteWebServiceDatasource {
  MockVisitanteWebServiceDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i28.VisitanteWebServiceModelInput>> getAllVisitante(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllVisitante,
          [token],
        ),
        returnValue: _i6.Future<List<_i28.VisitanteWebServiceModelInput>>.value(
            <_i28.VisitanteWebServiceModelInput>[]),
      ) as _i6.Future<List<_i28.VisitanteWebServiceModelInput>>);
}
