// Mocks generated by Mockito 5.4.4 from annotations
// in pcp/test/domain/repository/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pcp/domain/entities/variable/config.dart' as _i7;
import 'package:pcp/domain/errors/errors.dart' as _i6;
import 'package:pcp/domain/repositories/variable/config_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigRepository extends _i1.Mock implements _i3.ConfigRepository {
  @override
  _i4.Future<bool> hasConfig() => (super.noSuchMethod(
        Invocation.method(
          #hasConfig,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String> getSenhaConfig() => (super.noSuchMethod(
        Invocation.method(
          #getSenhaConfig,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSenhaConfig,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getSenhaConfig,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, num>> sendConfig(_i7.Config? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendConfig,
          [config],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, num>>.value(
            _FakeEither_0<_i6.Failure, num>(
          this,
          Invocation.method(
            #sendConfig,
            [config],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i6.Failure, num>>.value(
                _FakeEither_0<_i6.Failure, num>(
          this,
          Invocation.method(
            #sendConfig,
            [config],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, num>>);
}
